# Generated by Django 4.0.4 on 2022-05-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('pass1', models.CharField(max_length=50)),
                ('re_pass', models.CharField(max_length=50)),
            ],
        ),
    ]
