# Generated by Django 4.0.4 on 2022-05-18 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='your_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='your_pass',
            new_name='pass1',
        ),
    ]
